### ISSUE TITLE
Uncaught Error: Undefined class constant 'XML_PATH_DISABLE_CUSTOMER_REGISTRATION'

### ISSUE THREAD

**Issue by earlelnar** [sbodak/magento2-b2b-disable-customer-registration#4]
Hello Bodak,

I tried your module in Magento 2.3.4 but it throws an error 

`[error] 27008#27008: *16657 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined class constant 'XML_PATH_DISABLE_CUSTOMER_REGISTRATION' in /var/www/html/Magento/app/code/Bodak/DisableRegistration/Plugin/RegistrationPlugin.php:54`

In order to fix the issue, I updated line 32 and changed the constant to "XML_PATH_DISABLE_CUSTOMER_REGISTRATION".

![image](https://user-images.githubusercontent.com/14094984/75425707-34836880-597e-11ea-85a7-872659c0f279.png)

Thanks!

**Comment by sbodak** [comment]
@mazestricks ugh, thanks. Fixed.
